In [40]:
import numpy as np
marks=np.array([56,87,87,54,45,34])
print(marks[marks> 50])

[56 87 87 54]


In [56]:
marks=np.array([["vyshu",67],["sweety",90]])
print(marks[marks>65])5

NameError: name 'array' is not defined

In [25]:
arr=np.array([5,6,8,9,6,])
for i in arr:
    print (i)

5
6
8
9
6


In [19]:
arr=np.array([27,34,56,89])
for i in arr:
    print(i)

27
34
56
89


In [24]:
arr=np.array([[34,56],[89,43]])
print (arr)


[[34 56]
 [89 43]]


In [33]:
import numpy as np
first=np.array(["abhinaya","nithishma","vyshnavi","sweety"])
print(first[1])

nithishma


In [36]:
import numpy as np
first=np.array(["abhinaya","nithishma","vyshnavi","sweety"])
print(first[1])
print(first[3])

nithishma
sweety


In [39]:
for i in np.nditer(arr):
    print(i)

5
6
8
9
6


In [42]:
import numpy as np
first=np.array([["sweety","vyshu"],["abhi","vyshu"],["sweety","abhi"]])
print(first[0])
print(first[1])

['sweety' 'vyshu']
['abhi' 'vyshu']


In [44]:
marks=([45,56,78,89])
for i in np.nditer(marks):
    print(i)

(array(45), array(56), array(78), array(89))


In [45]:
arr1=([3,5,5,8,9,7])
arr2=([4,4,8,7,6,3])
print(arr1+arr2)

[3, 5, 5, 8, 9, 7, 4, 4, 8, 7, 6, 3]


In [46]:
arr1=np.array([3,5,5,8,9,7])
arr2=np.array([4,4,8,7,6,3])
print(arr1+arr2)

[ 7  9 13 15 15 10]


In [47]:
arr1=(['cat','mat','bat','dog'])
arr2=(['dinny','chinny','pinny'])
print(arr1+arr2)

['cat', 'mat', 'bat', 'dog', 'dinny', 'chinny', 'pinny']


In [48]:
a=([3,4,5,7])
b=([4,7,9,7])
c=np.concatenate((a,b))
print(c)

[3 4 5 7 4 7 9 7]
