In [2]:
import numpy as np
arr=np.array([57,45,90,54,45])
x=np.where(arr==45)
print(x)

(array([1, 4]),)


In [7]:
import numpy as np
arr=np.array([57,45,90,54,45])
x=np.sort(arr==45)
print(x)

[False False False  True  True]


In [6]:
import numpy as np
arr=np.array([57,45,90,54,45])
x=np.sort(arr)
print(x)

[45 45 54 57 90]


In [5]:
import numpy as np
arr1=([2,3,4,5])
arr2=([3,5,6,7])
arr3=np.array((arr1+arr2))
print(arr3)

[2 3 4 5 3 5 6 7]


In [6]:
arr=np.array([10,20,30,40,50,60])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.average(arr))
print(np.mean(arr))

210
10
60
35.0
35.0


In [7]:
print(np.power(arr,2))

[ 100  400  900 1600 2500 3600]


In [ ]:
666666666666666666666666665