In [2]:
import numpy as np
arr=np.array([12,20,30,40])
print(arr)

[12 20 30 40]


In [3]:
arr=np.array([[10,20],[20,30],[30,80]])
print(arr)

[[10 20]
 [20 30]
 [30 80]]


In [7]:
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
print(a+b)
print(b-a)
print(a*b)
print(b/a)

[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]
[0.1 0.1 0.1 0.1]


In [15]:
abc=np.array([10,20,30,40])
print(np.max(abc))
print(np.min(abc))
print(np.sum(abc))
print(np.average(abc))

40
10
100
25.0
25.0


In [26]:
def count(n):
  if n==3:
     return
  print(n)
  count(n-1)

count(5)

5
4


In [5]:
def count(n):
  if n==0:
      return
  print("hello")
  count(n-1)

count(5)

hello
hello
hello
hello
hello
