In [6]:
import numpy as np
sales = np.array([120,340,560,230,150])
products = np.array(["A","B","C","D","E"])
print(products[sales>200])

['B' 'C' 'D']


In [5]:
print(np.average(sales))

280.0


In [7]:
print(np.sort(sales))

[120 150 230 340 560]


In [8]:
print(np.vstack(sales))

[[120]
 [340]
 [560]
 [230]
 [150]]


In [10]:
print(np.hstack(sales))

[120 340 560 230 150]


In [14]:
print(np.vstack(products))
        

[['A']
 ['B']
 ['C']
 ['D']
 ['E']]
