In [1]:
import numpy as np
a=np.array([1,5,8,9])
b=np.array([2,4,3,7])
print(np.hstack((a,b)))

[1 5 8 9 2 4 3 7]


In [2]:
import numpy as np
a=np.array([1,5,8,9])
b=np.array([2,4,3,7])
print(np.vstack((a,b)))

[[1 5 8 9]
 [2 4 3 7]]


In [3]:
arr=np.array([2,5,8,3])
print(arr +5)

[ 7 10 13  8]


In [5]:
arr=np.array([[2,4,6,],[5,3,6]])
print(arr +[3,8,4])

[[ 5 12 10]
 [ 8 11 10]]
